export const diasConteudo = [
  {
    dia: 1,
    titulo: 'A Porta do Sacrário',
    misterio_destaque: '1º Gozoso — A Anunciação do Anjo a Maria',
    reflexao: 'Você está aqui. Talvez com o coração apertado, talvez com uma esperança tímida que mal se atreve a existir. Não importa como chegou — se foi por curiosidade, por dor, por uma promessa sussurrada de madrugada ou por uma amiga que disse "tenta, vai." O que importa é que você está na porta. E ela já está aberta.\n\nO Sacrário é o lugar mais silencioso de uma igreja. É onde Jesus está, reservado, esperando. E é também o nome dessa jornada — porque nos próximos 21 dias, você vai entrar nesse silêncio sagrado. Não com pressa. Não com obrigação. Mas como quem entra na casa da própria mãe depois de um dia longo, tira os sapatos e finalmente respira.\n\nO Rosário é a oração que vai te acompanhar nessa jornada. Se você não sabe rezar de cor, tudo bem. Se não entende os Mistérios, tudo bem. O Rosário não é uma prova — é um encontro. A repetição da Ave Maria não é mecânica: é como o embalo de uma mãe ninando o filho. O ritmo acalma. A repetição abre espaço. E nesse espaço, Deus fala. Todos os dias, você vai rezar o Rosário completo — os quatro conjuntos de Mistérios: Gozosos, Luminosos, Dolorosos e Gloriosos. São 20 dezenas. Leva tempo. Mas é nesse tempo que a transformação acontece. Hoje, durante os Mistérios Gozosos, dê atenção especial ao primeiro — a Anunciação: o dia em que Maria recebeu um convite que mudou tudo. Assim como você está recebendo agora.\n\nExiste uma frequência espiritual — uma sintonia entre o seu coração e o coração de Maria — que se constrói na oração diária. Hoje, você está ligando o rádio pela primeira vez. Vai ter estática. Vai ter ruído. Mas o sinal já existe. E a cada dia que você rezar, ele vai ficando mais nítido. Essa é a Frequência de Maria. E nos próximos 21 dias, você vai aprender a sintonizá-la.',
    titulo_audio: 'Abertura do Sacrário',
    sugestao_intencao: 'Ofereço essa oração por aquilo que me trouxe até aqui — a dor, a esperança ou o pedido que carrego no coração.',
  },
  {
    dia: 2,
    titulo: 'O Sim de Maria',
    misterio_destaque: '1º Gozoso — A Anunciação (o Sim)',
    reflexao: 'Teve um dia em que uma menina de Nazaré ouviu algo impossível. Um anjo disse: "Você vai ser mãe do Salvador." Maria não entendeu. Como poderia? Era jovem, simples, noiva de um carpinteiro. Nada na vida dela apontava pra isso. E mesmo sem entender, ela disse sim. "Faça-se em mim segundo a Tua palavra." Não foi um sim de quem tinha certeza. Foi um sim de quem confiava.\n\nQuantas vezes a vida te pede um sim que você não entende? Um diagnóstico que não faz sentido. Um caminho que parece errado. Uma espera que parece longa demais. Maria sabe o que é isso. Ela não foi poupada da dúvida — foi sustentada através dela.\n\nQuando você reza o primeiro Mistério Gozoso — a Anunciação — você contempla exatamente esse momento: o anjo, a pergunta, o medo, e o sim. Hoje, nas dez Ave Marias dessa primeira dezena, imagine Maria dizendo sim. E imagine você dizendo o seu sim a essa jornada. Não o sim perfeito — o sim possível. Com as mãos tremendo e o coração aberto.\n\nA Frequência de Maria se sintoniza no sim. No sim diário de parar tudo e rezar. No sim de confiar mesmo quando não entende. Ontem você ligou o rádio. Hoje, o sinal ficou um pouco mais claro. Amanhã, mais ainda. Conta por conta. Dia por dia. Sim por sim.',
    titulo_audio: 'O Sim que Muda Tudo',
    sugestao_intencao: 'Peço a graça de confiar em Deus naquilo que ainda não entendo na minha vida.',
  },
  {
    dia: 3,
    titulo: 'A Visitação',
    misterio_destaque: '2º Gozoso — A Visitação de Maria a Santa Isabel',
    reflexao: 'Depois de receber a notícia mais extraordinária da história, Maria não ficou parada. O Evangelho diz que ela "foi apressada" até a casa de Isabel, sua prima idosa e grávida. Quatro dias a pé pelas montanhas. Maria não foi por obrigação — foi porque esse é o movimento natural do amor: quando o coração transborda, ele corre ao encontro de quem precisa.\n\nQuando as duas se encontraram, o bebê de Isabel saltou no ventre. E Isabel disse a frase que repetimos em cada Ave Maria: "Bendita és tu entre as mulheres." Naquele abraço entre duas mulheres, numa casa simples da Judeia, o céu tocou a terra.\n\nHoje, quando rezar a segunda dezena dos Mistérios Gozosos — a Visitação — contemple esse encontro. E perceba: Maria faz o mesmo movimento em direção a você. Ela não espera que você vá até ela. Ela vem. Apressada. Como foi à casa de Isabel. Porque sabe que você precisa. E cada Ave Maria que você reza é o eco daquele abraço entre Isabel e Maria, repetido agora entre Maria e você.\n\nA Frequência de Maria não é algo que acontece só na oração. É algo que começa a vazar pra vida. Talvez hoje, depois de rezar, você sinta vontade de ligar pra alguém. De visitar alguém. De perguntar "como você está?" e realmente ouvir a resposta. Esse é o sinal da frequência funcionando: o amor que transborda.',
    titulo_audio: 'Ela Vem ao Seu Encontro',
    sugestao_intencao: 'Rezo por alguém que precisa de uma visita, uma ligação ou uma palavra de consolo — e que eu tenha coragem de ir.',
  },
  {
    dia: 4,
    titulo: 'O Manto de Proteção',
    misterio_destaque: '3º Gozoso — O Nascimento de Jesus em Belém',
    reflexao: 'Numa noite fria em Belém, sem lugar na hospedaria, Maria deu à luz. Não num berço de ouro — numa manjedoura, no meio de palha e animais. Deus se fez pequeno, frágil, próximo. Veio não como rei num palácio, mas como bebê no frio, protegido apenas pelos braços de Maria e pelo manto que ela tinha.\n\nExiste uma imagem de Nossa Senhora que atravessa os séculos: ela de braços abertos, com um manto imenso que cobre todos os que se abrigam debaixo dele. É a Nossa Senhora do Manto. Essa imagem nasce daquela noite em Belém: Maria cobrindo Jesus do frio com o pouco que tinha. E agora, faz o mesmo com você.\n\nQuando rezar a terceira dezena dos Gozosos — o Nascimento — contemple essa cena: o estábulo, o frio, o bebê, e Maria cobrindo. E pense: do que você precisa ser coberta hoje? Do frio do medo? Da intempérie da ansiedade? Maria estende o manto sobre você com cada Ave Maria que você reza. Uma Ave Maria, uma camada de proteção. Dez Ave Marias, um manto inteiro.\n\nQuatro dias. A estática está cedendo. Talvez você ainda não sinta uma transformação dramática — e tudo bem. A Frequência de Maria não é uma explosão. É uma construção. Como o calor que o terço absorve das suas mãos: no começo está frio, mas depois de um tempo, aquece. Você está aquecendo o canal.',
    titulo_audio: 'Debaixo do Manto',
    sugestao_intencao: 'Entrego nas mãos de Maria o meu maior medo — aquele que me tira o sono e que eu carrego sozinha.',
  },
  {
    dia: 5,
    titulo: 'Lágrimas aos Pés da Cruz',
    misterio_destaque: '5º Doloroso — A Crucificação e Morte de Jesus',
    reflexao: 'Hoje, quebramos a sequência dos Gozosos. Porque o acolhimento verdadeiro não é só de alegria — é também da dor. E existe uma dor que talvez você carregue e que precisa de espaço antes de continuar.\n\nMaria chorou. A gente às vezes esquece disso. Coloca ela num pedestal tão alto que esquece que era uma mãe. Uma mãe que viu o filho ser preso, torturado e morto. O Evangelho de João diz com uma simplicidade cortante: "Junto à cruz de Jesus estava sua mãe." Estava. Não fugiu. Não desmaiou. Ficou ali, com os pés no chão, olhando pra cima, segurando a dor nos dentes.\n\nHoje, durante o Rosário completo, dê atenção especial aos Mistérios Dolorosos. E no quinto — a Crucificação — eu te peço que contemple Maria aos pés da cruz. Não como uma cena distante de dois mil anos atrás. Mas como alguém que entende a sua dor agora. Porque a mãe que ficou de pé ao lado da cruz é a mesma mãe que fica de pé ao lado da sua.\n\nSe você está passando por algo insuportável — uma perda, uma solidão que grita, um cansaço da alma — saiba que hoje a oração não pede que você seja forte. Pede que você seja honesta. Chore se precisar. Suas lágrimas são oração. Maria chorou. E a Frequência de Maria não é só de paz — é também de dor transformada. A estática maior que existe é a dor que a gente engole sozinha. Quando você entrega, o canal limpa.',
    titulo_audio: 'A Mãe que Ficou de Pé',
    sugestao_intencao: 'Ofereço as minhas lágrimas e a dor que não conto pra ninguém — que Maria as transforme em graça.',
  },
  {
    dia: 6,
    titulo: 'O Abraço de Maria',
    misterio_destaque: '4º Gozoso — A Apresentação de Jesus no Templo',
    reflexao: 'Ontem foi pesado. Você visitou a cruz, tocou nas suas dores, chorou. Hoje, o Rosário volta aos Gozosos — porque depois da dor, Maria te oferece colo.\n\nQuarenta dias após o nascimento de Jesus, Maria o levou ao Templo para apresentá-lo ao Senhor. O gesto de uma mãe que entrega o filho mais precioso nas mãos de Deus. Não porque não o amasse — mas porque o amava demais para não devolvê-lo a quem o deu. Foi no Templo que Simeão profetizou: "Uma espada traspassará a tua alma." Maria ouviu. Segurou Jesus mais forte. E seguiu em frente.\n\nO Imaculado Coração de Maria não é um conceito teológico frio. É o coração de uma mãe que entregou tudo — e mesmo assim continuou amando. É esse coração que bate por você agora. Quando você reza a quarta dezena dos Gozosos, imagine Maria no Templo, segurando Jesus nos braços, ouvindo a profecia da dor que viria. E ainda assim, abraçando. Ainda assim, amando.\n\nSeis dias de oração. A Frequência de Maria já está diferente do primeiro dia. A estática diminuiu. O momento de silêncio chega mais rápido. Talvez você tenha notado que o terço já esquenta mais depressa nas suas mãos — porque as suas mãos já conhecem o caminho. Isso é a frequência se consolidando.',
    titulo_audio: 'Imersão no Imaculado Coração',
    sugestao_intencao: 'Peço a Maria que cuide de mim hoje como eu cuido dos outros — que eu me permita receber colo.',
  },
  {
    dia: 7,
    titulo: 'O Silêncio de Nazaré',
    misterio_destaque: '5º Gozoso — O Encontro do Menino Jesus no Templo',
    reflexao: 'A maior parte da vida de Maria foi silêncio. Trinta anos em Nazaré, sem milagres, sem multidões. Acordar, fazer o pão, lavar a roupa, varrer a casa, cuidar do filho. Todo dia. Por décadas. E o Evangelho resume tudo isso numa frase: "Maria guardava todas essas coisas no coração."\n\nNo quinto Mistério Gozoso, Jesus desaparece aos doze anos e é encontrado no Templo, conversando com os doutores. Maria e José passaram três dias de angústia procurando. Quando o encontraram, Jesus disse algo que eles não entenderam: "Não sabíeis que eu devia estar na casa de meu Pai?" E Maria — mais uma vez — guardou no coração. Não publicou, não proclamou. Guardou.\n\nA gente quer que Deus fale com trovão. Quer sinais claros, respostas óbvias. Mas Maria aprendeu a ouvir Deus no barulho da vassoura, no cheiro da lenha, no riso do filho brincando. Ela encontrou o sagrado dentro do ordinário. Talvez a sua vida pareça ordinária demais pra Deus se importar. Mas Nazaré era assim. E foi ali que o Salvador cresceu.\n\nHoje encerra o primeiro bloco da jornada. Sete dias. Uma semana inteira de oração. A Frequência de Maria agora não é mais só estática — há um sinal. Baixo, constante, como o murmúrio de um riacho que você ainda não vê, mas ouve. Amanhã começa o Bloco 2: Transformação. Mas hoje, fique no silêncio. É nele que tudo cresce.',
    titulo_audio: 'Ouvir no Silêncio',
    sugestao_intencao: 'Que eu aprenda a ouvir Deus no silêncio da minha rotina — na cozinha, no trabalho, no caminho de casa.',
  },
  {
    dia: 8,
    titulo: 'O Terço na Mão, a Fé no Coração',
    misterio_destaque: '1º Luminoso — O Batismo de Jesus no Jordão',
    reflexao: 'Uma semana. Sete dias consecutivos de oração. Você pode não achar grande coisa — mas é. Num mundo que te puxa pra mil direções, você escolheu parar e rezar. Sete vezes seguidas. Isso é disciplina. E disciplina, na vida espiritual, não é castigo — é raiz.\n\nA partir de hoje, o destaque da contemplação vai para os Mistérios Luminosos. O primeiro é o Batismo de Jesus: o momento em que Ele entra nas águas do Jordão e o Pai diz "Este é o meu Filho amado." É o início da missão. O começo público de algo que foi preparado em silêncio durante trinta anos.\n\nVocê também está no seu batismo de fogo. A primeira semana foi de preparação — de acolhimento, de colo, de entrega. Agora, a missão começa. E a missão é simples: não parar. Continuar. Todo dia. Conta por conta. Mesmo quando não sentir nada. Mesmo quando a mente vagar. Mesmo quando o cansaço disser que hoje você pode pular.\n\nOs santos chamavam o Rosário de arma espiritual. São Pio não largava o terço nem dormindo. Não por superstição — por necessidade. Porque sabia que a constância da oração repetida é o que sustenta a alma quando tudo mais falha. O poder não está na novidade. Está na repetição. Está em voltar ao mesmo gesto, à mesma oração, à mesma conta — e encontrar Deus ali, de novo, diferente a cada vez.\n\nA frequência agora precisa de firmeza. Os primeiros dias foram sobre sintonizar. Os próximos são sobre não perder a sintonia.',
    titulo_audio: 'A Arma nas Suas Mãos',
    sugestao_intencao: 'Peço firmeza para não desistir da oração — mesmo nos dias em que não sentir vontade.',
  },
  {
    dia: 9,
    titulo: 'A Espada de Dor',
    misterio_destaque: '1º Doloroso — A Agonia de Jesus no Horto das Oliveiras',
    reflexao: 'No Horto das Oliveiras, na noite antes de morrer, Jesus suou sangue. Pediu ao Pai que tirasse aquele cálice. Pediu três vezes. Não foi atendido. E disse: "Não a minha vontade, mas a Tua." O Salvador do mundo teve medo. Tremeu. Pediu pra não sofrer. E quando a resposta foi silêncio, obedeceu.\n\nMaria não estava no Horto — mas conhecia a agonia do filho porque conhecia a sua própria. A espada que Simeão profetizou no Templo atravessou a alma dela lentamente, ao longo de toda a vida. Não de uma vez. Dia por dia. Gota por gota.\n\nO sofrimento faz parte. Não porque Deus quer que a gente sofra — mas porque o mundo é quebrado. A diferença é o que fazemos com a dor. Sozinha, ela esmaga. Oferecida, transforma. Na tradição católica, existe o ofertório: unir o seu sofrimento ao de Cristo. Isso não é masoquismo. É dizer: "essa dor não é em vão. Ela faz parte de algo maior."\n\nQuando rezar o primeiro Mistério Doloroso — a Agonia no Horto — contemple Jesus ajoelhado entre as oliveiras. E traga a sua própria agonia. Aquilo que te tira o sono. Que te faz suar frio. E ofereça. A Frequência de Maria se refina no ofertório — porque o canal mais limpo entre você e Deus é o que passa pela verdade crua, sem disfarce.',
    titulo_audio: 'Oferecer a Dor',
    sugestao_intencao: 'Ofereço um sofrimento específico que carrego — e peço que ele se torne oração por quem eu amo.',
  },
  {
    dia: 10,
    titulo: 'A Água e o Vinho',
    misterio_destaque: '2º Luminoso — As Bodas de Caná (A Transformação da Água em Vinho)',
    reflexao: 'Numa festa de casamento em Caná, o vinho acabou. Uma humilhação social — naquela cultura, ficar sem vinho era vergonha pública. Os noivos não sabiam o que fazer. Mas Maria percebeu. E fez duas coisas que definem quem ela é: primeiro, foi a Jesus e disse "eles não têm vinho." Segundo, disse aos servos: "Fazei tudo o que Ele vos disser."\n\nMaria não fez o milagre. Ela intermediou. Ela viu a necessidade, levou a Deus e orientou a obediência. E Jesus transformou água em vinho — o ordinário em extraordinário.\n\nEsse é o segundo Mistério Luminoso. E é exatamente o que está acontecendo com você nesta jornada. Você trouxe água — sua vida ordinária, suas dores, suas rotinas. E a oração está transformando essa água em algo que você ainda não reconhece completamente. Não de uma vez. Não com estrondo. Mas de dentro pra fora, silenciosamente, como o vinho que encheu as talhas sem que ninguém visse o momento exato da mudança.\n\nDez dias. A Frequência de Maria já não é mais estática com lampejos de sinal. Agora é sinal com lampejos de estática. A inversão aconteceu. Você talvez não perceba — porque quem está dentro da transformação raramente percebe enquanto ela acontece. Mas o canal está mais nítido. A água já está virando vinho.',
    titulo_audio: 'A Transformação Silenciosa',
    sugestao_intencao: 'Peço a Maria que interceda por uma situação na minha vida que precisa de transformação.',
  },
  {
    dia: 11,
    titulo: 'O Jardim Fechado',
    misterio_destaque: '4º Luminoso — A Transfiguração de Jesus',
    reflexao: 'No Monte Tabor, longe das multidões, Jesus se transfigurou. O rosto brilhou como o sol, as vestes ficaram brancas como a luz. Pedro, Tiago e João viram a glória — mas só porque estavam ali, no alto, no lugar reservado. Quem ficou embaixo não viu nada.\n\nA vida espiritual precisa de um lugar reservado. O Cântico dos Cânticos chama Maria de "jardim fechado, fonte selada" — um espaço íntimo onde só Deus entra. Nos últimos onze dias, você está construindo esse jardim dentro de si. Cada oração foi uma semente. Cada lágrima, rega. Cada silêncio, sol.\n\nMas o jardim precisa de portão. Precisa de proteção. Não por egoísmo — por cuidado. O que está nascendo em você é frágil ainda. Se você abre demais, se deixa o barulho do mundo entrar sem filtro, as mudas morrem antes de florescer. O Rosário é o muro desse jardim. A repetição é a cerca. A constância é a tranca.\n\nA Frequência de Maria se fortalece no recolhimento. Não no isolamento — no recolhimento. Há diferença: isolamento é fuga; recolhimento é escolha. Você está escolhendo proteger o que Deus está plantando.',
    titulo_audio: 'O Jardim Secreto',
    sugestao_intencao: 'Que eu proteja o que Deus está cultivando em mim — e saiba fechar a porta para o que enfraquece a minha fé.',
  },
  {
    dia: 12,
    titulo: 'A Estrela do Mar',
    misterio_destaque: '4º Doloroso — Jesus Carrega a Cruz (Via Crucis)',
    reflexao: 'Os marinheiros antigos, perdidos em alto-mar, olhavam para uma estrela — a Stella Maris — e sabiam para onde ir. A Igreja deu esse título a Maria: Estrela do Mar. A luz que guia na escuridão.\n\nNo quarto Mistério Doloroso, Jesus carrega a cruz pelas ruas de Jerusalém. Cai. Levanta. Cai de novo. A tradição diz que Maria estava ali, na multidão, acompanhando cada passo. Não podia tirar a cruz. Não podia carregar por ele. Mas podia estar presente. E estava.\n\nExistem noites na vida que parecem não ter fim. Noites de insônia, de dúvida, de desespero. Noites em que você se sente carregando uma cruz que ninguém vê. Nessas noites, Maria é a estrela. Ela não tira a cruz. Não acalma o mar de imediato. Mas brilha. E quem olha pra cima encontra direção.\n\nDoze dias. A frequência está firme o suficiente para te sustentar nas noites escuras. Esse é o teste real da transformação: não é sentir paz quando tudo vai bem — é manter a sintonia quando tudo desmorona. Se o terço na sua mão é o leme do barco, Maria é a estrela. Enquanto você olhar pra ela, não se perde.',
    titulo_audio: 'Luz no Mar Escuro',
    sugestao_intencao: 'Rezo por luz e direção num momento da minha vida em que me sinto perdida ou sem rumo.',
  },
  {
    dia: 13,
    titulo: 'O Coração que Perdoa',
    misterio_destaque: '5º Doloroso — A Crucificação e Morte de Jesus',
    reflexao: 'Na cruz, com o corpo destroçado, Jesus disse: "Pai, perdoa-lhes, porque não sabem o que fazem." Perdoou os que o mataram. No ápice da dor, escolheu o perdão. E Maria, aos pés da cruz, repetiu isso no silêncio do coração.\n\nPerdoar é a coisa mais difícil que a oração pede. Mais difícil do que crer. Mais difícil do que esperar. Porque exige soltar algo que parece nosso por direito: a raiva, a mágoa, o "eu tenho razão de sentir o que sinto." E você tem razão. Mas o perdão não nega a ferida — recusa que a ferida defina quem você é.\n\nQuando rezar o quinto Mistério Doloroso — a Crucificação — contemple Jesus dizendo "perdoa-lhes." E traga ao coração o rosto de alguém que você precisa perdoar. Não precisa sentir vontade. Perdão não é sentimento — é decisão. É dizer: "não vou carregar isso mais." Maria te empresta a força que você não tem sozinha.\n\nA Frequência de Maria e o perdão estão ligados. A mágoa é a estática mais pesada que existe. Gruda no canal e não sai com oração bonita — sai com decisão. Quando você solta, o sinal dá um salto. Não porque o perdão seja fácil. Mas porque é libertador.',
    titulo_audio: 'Soltar pra Ser Livre',
    sugestao_intencao: 'Peço forças para perdoar alguém que me machucou — ou para me perdoar por algo que ainda carrego.',
  },
  {
    dia: 14,
    titulo: 'A Coroa de Rosas',
    misterio_destaque: '5º Luminoso — A Instituição da Eucaristia',
    reflexao: 'A palavra "rosário" vem do latim rosarium — jardim de rosas. A tradição diz que cada Ave Maria rezada com o coração se torna uma rosa aos pés de Nossa Senhora. Duas semanas. Centenas de Ave Marias. Centenas de rosas.\n\nNo quinto Mistério Luminoso, Jesus pega o pão e diz: "Isto é o meu corpo, entregue por vós." A Eucaristia é a entrega total — Deus se dando inteiro. E o Rosário espelha isso. Cada Ave Maria é uma entrega: de tempo, de atenção, de voz. Pequena, repetida, constante. Como o pão partido — simples por fora, infinito por dentro.\n\nOlhe para trás. Lembra da mulher que entrou pela porta do Sacrário no Dia 1? Lembra do medo, da incerteza? Agora, quatorze rosários depois, você está aqui. Cada manhã ou noite que parou tudo pra rezar, cada conta entre os dedos, cada intenção murmurada — uma rosa. Vermelha de amor. Branca de entrega. Dourada de fé. Maria recebeu cada uma.\n\nAmanhã começa o último bloco: Consagração. A Frequência de Maria agora é clara. Nítida. O canal está aberto e limpo. Ainda virão interferências — a vida não para de ter ruído. Mas o sinal agora é forte o suficiente para não se perder. Você não está mais sintonizando. Está transmitindo.',
    titulo_audio: 'Uma Rosa por Ave Maria',
    sugestao_intencao: 'Agradeço por cada dia que rezei até aqui e ofereço essa coroa de rosas pela minha família.',
  },
  {
    dia: 15,
    titulo: 'A Chave do Sacrário',
    misterio_destaque: '1º Glorioso — A Ressurreição de Jesus',
    reflexao: 'No primeiro Mistério Glorioso, a pedra do sepulcro é rolada. O que estava fechado se abre. O que estava morto vive. Jesus ressuscita. Não como quem volta ao normal — como quem supera definitivamente a morte.\n\nExiste uma chave pequena e dourada que o sacristão usa pra abrir o Sacrário de uma igreja. Dentro dele, Jesus está presente — vivo, real. Nos últimos catorze dias, a oração foi girando uma chave dentro de você. Devagar, conta a conta, dia a dia. E agora, no décimo quinto dia, o trinco cede. O sacrário do seu coração se abre.\n\nAbrir o coração pra Deus de verdade é assustador. Significa parar de controlar. Confiar que Ele sabe o que faz, mesmo quando não entende. Mas é também o gesto mais libertador que existe. Porque o que está do outro lado da porta não é cobrança — é amor.\n\nA Frequência de Maria agora opera em modo aberto. O canal não só transmite — recebe. E o que você recebe, a partir de agora, não é mais só consolo. É poder. É missão. É envio. A consagração começou.',
    titulo_audio: 'A Pedra Rolada',
    sugestao_intencao: 'Que o que estava morto na minha vida ressuscite — uma esperança, um sonho, um relacionamento, uma fé adormecida.',
  },
  {
    dia: 16,
    titulo: 'O Terço dos Anjos',
    misterio_destaque: '2º Glorioso — A Ascensão de Jesus ao Céu',
    reflexao: 'No segundo Mistério Glorioso, Jesus sobe ao céu. Os discípulos olham pra cima enquanto Ele desaparece entre as nuvens. E dois anjos aparecem e dizem: "Por que ficais olhando para o céu?" É como se dissessem: Ele subiu — mas a missão desceu. Agora é com vocês.\n\nA tradição católica diz que quando alguém reza o Rosário, os anjos se juntam. São Pio de Pietrelcina via anjos trazendo rosários de todo o mundo. Não é fantasia — é a fé que enxerga além do visível. Cada Ave Maria que você reza não fica parada na sua sala. Ela sobe. É levada por mãos que você não vê até um Deus que vê tudo.\n\nDezesseis dias. A oração não é mais um exercício — é uma via de comunicação aberta. A Frequência de Maria está tão estabilizada que agora o desafio não é manter a sintonia — é sustentar a potência. Porque a frequência não serve só pra você se sentir bem. Serve pra alcançar. Pra chegar onde as suas mãos não chegam. Cada Ave Maria que sai da sua boca é levada por anjos até onde é mais necessária.\n\nReze hoje com essa consciência: você não reza sozinha. Há uma rede invisível de intercessão ao seu redor.',
    titulo_audio: 'A Oração que Sobe',
    sugestao_intencao: 'Confio ao meu anjo da guarda a minha intenção mais urgente — aquela que precisa chegar ao céu com pressa.',
  },
  {
    dia: 17,
    titulo: 'A Mãe de Todos os Filhos',
    misterio_destaque: 'conexão com o gesto da Cruz — "Eis a tua mãe"',
    reflexao: 'Na cruz, Jesus olhou pra Maria e disse a João: "Eis a tua mãe." Naquele momento, Maria se tornou mãe de todos. Não de um filho — de cada ser humano. Mãe sua. Minha. De quem reza e de quem não reza.\n\nIsso muda a oração. Porque quando você reza, não reza só por você. Cada Ave Maria carrega o mundo inteiro. A vizinha que está doente. A mãe do outro lado do país chorando pelo filho. O preso que ninguém visita. Maria distribui as graças como mãe: conforme cada filho precisa.\n\nDezessete dias. A frequência agora tem alcance. O que antes era um sinal pessoal — entre você e Maria — agora se expande. A oração de uma mulher sintonizada na Frequência de Maria tem um raio de alcance que ela mesma desconhece. Reze hoje com generosidade. Reze para além de si mesma.\n\nA consagração não é sobre se recolher — é sobre transbordar. Quem está cheia, derrama. E o que derrama de você agora é oração por quem precisa.',
    titulo_audio: 'Rezar pelo Mundo',
    sugestao_intencao: 'Hoje rezo por alguém que não tem quem reze por ela — um nome que o Espírito Santo colocar no meu coração.',
  },
  {
    dia: 18,
    titulo: 'O Fogo do Espírito',
    misterio_destaque: '3º Glorioso — A Descida do Espírito Santo (Pentecostes)',
    reflexao: 'Depois que Jesus subiu, os apóstolos se trancaram com medo. E quem estava ali? Maria. No meio dos homens perdidos, ela estava. Rezando. Esperando.\n\nE então, Pentecostes. Vento forte. Línguas de fogo. Os medrosos saíram pra rua pregando. O medo virou coragem. O silêncio virou voz. Maria não recebeu o Espírito como quem recebe pela primeira vez — Ele já vivia nela desde a Anunciação. Mas ela estava ali porque sabia que a comunidade precisava da sua presença para que o fogo viesse.\n\nDezoito dias. Faltam três. E agora a pergunta muda: não é mais "o que essa jornada fez por mim?" — é "o que eu faço com o que essa jornada me deu?" A Frequência de Maria não é pra ficar guardada. É pra incendiar. A mulher que reza o Rosário com constância não é só alguém que tem paz interior — é alguém que leva paz onde pisa. Essa é a missão. Essa é a chama.\n\nO fogo do Espírito não é metáfora confortável. É poder real. A coragem de viver a fé sem vergonha. De rezar sem esconder. De ser diferente do que o mundo espera. O terço na mão não é acessório — é declaração.',
    titulo_audio: 'Acende em Mim',
    sugestao_intencao: 'Peço coragem para viver minha fé sem vergonha — em casa, no trabalho, diante de quem duvida.',
  },
  {
    dia: 19,
    titulo: 'A Rainha do Céu',
    misterio_destaque: '5º Glorioso — A Coroação de Maria como Rainha do Céu',
    reflexao: 'A menina de Nazaré que amassava pão, que lavava roupa, que fugiu pro Egito com um bebê nos braços — agora usa uma coroa de estrelas. Rainha do Céu. Não porque quis — porque o amor a levou até lá.\n\nNo quinto Mistério Glorioso, Maria é coroada. A coroa não é de ouro — é de obediência, de silêncio, de amor vivido no cotidiano, de dor transformada em entrega. É a coroa de quem não buscou glória, mas recebeu glória porque buscou Deus.\n\nE se Maria é Rainha, você é filha de Rainha. Isso muda a maneira como você se vê. Não é arrogância — é identidade. Filha de Rainha não abaixa a cabeça pra vergonha. Não se define pela falha. Caminha com dignidade, mesmo nos dias cinzentos. O terço na mão é o brasão da sua casa real.\n\nDezenove dias de frequência. E agora, a transmissão tem autoridade. Não é mais o murmúrio tímido do Dia 1. É a voz clara de quem sabe de quem é filha. Quem sabe de onde vem. E pra onde vai.',
    titulo_audio: 'Filha de Rainha',
    sugestao_intencao: 'Que eu nunca esqueça quem eu sou — filha de Deus, filha de Rainha — mesmo nos dias em que o mundo me fizer sentir pequena.',
  },
  {
    dia: 20,
    titulo: 'A Última Conta',
    misterio_destaque: '4º Glorioso — A Assunção de Maria ao Céu',
    reflexao: 'Amanhã é o último dia. Hoje é a véspera.\n\nNo quarto Mistério Glorioso, Maria é elevada ao céu de corpo e alma. Não como quem morre e abandona o mundo — como quem é chamada pra casa depois de uma missão cumprida. Maria viveu tudo: a alegria, a dor, o silêncio, a perda, a espera. E no final, foi levantada. Inteira. Corpo e alma. Sem deixar nada pra trás.\n\nO que esses vinte dias fizeram com você? Pode ser algo grande — um perdão, uma cura, uma decisão. Ou algo sutil — uma paz que antes não existia. Uma conversa com Deus que agora acontece naturalmente. Um terço que já é extensão da sua mão. Você foi elevada. Não ao céu — mas acima de onde estava.\n\nA Frequência de Maria amanhã atinge o ponto mais alto. Mas hoje é o dia de gratidão pelo caminho. Cada conta que passou entre seus dedos nesses vinte dias foi um degrau. A jornada não acaba amanhã — amanhã é o começo do resto da sua vida de oração.',
    titulo_audio: 'Véspera da Consagração',
    sugestao_intencao: 'Agradeço por cada dia desta jornada e peço a graça de nunca mais largar o terço.',
  },
  {
    dia: 21,
    titulo: 'A Frequência de Maria',
    misterio_destaque: 'Todos. Este é o dia da consagração.',
    reflexao: 'Você chegou.\n\nVinte e um dias. Centenas de Ave Marias. Quatro conjuntos de Mistérios contemplados — os Gozosos do encontro, os Dolorosos da entrega, os Luminosos da transformação, os Gloriosos da vitória. Horas de silêncio. Lágrimas que viraram oração. Medos que viraram entrega. Uma coroa de rosas construída conta a conta.\n\nA Frequência de Maria não é metáfora. É o que aconteceu com você. A oração diária sintonizou o seu coração numa frequência de paz, de fé e de amor que antes era estática. Você limpou o canal. Dia a dia. Conta a conta. E agora, o que Maria sempre esteve transmitindo, você ouve com clareza: você é amada. Protegida. Nunca esteve sozinha.\n\nA jornada termina. A frequência, não. Enquanto o terço estiver na sua mão, a transmissão continua. A pergunta agora não é "o que conquistei?" — é "como vivo isso daqui pra frente?" E a resposta é simples: continue. Não como obrigação. Como respiração. A mulher que você é agora — a que reza, a que perdoa, a que carrega fogo, a que é filha de Rainha — essa mulher não existia vinte e um dias atrás. E ela não precisa desaparecer amanhã.',
    titulo_audio: 'Para Sempre Sintonizada',
    sugestao_intencao: 'Consagro minha vida, minha família e meu futuro ao Imaculado Coração de Maria — para sempre sintonizada na Sua frequência.',
  },
];
